### ISSUE TITLE
Red Black Tree Implementation

### ISSUE THREAD

**Issue by jdrco** [jdrco/baltree#1]
**Part 1:** You are required to create your own implementation for a red-black tree. Your library must allow the user to perform the following operation:
- [x] Insert a node to the red-black tree.
- [x] Delete a node from the red-black tree.
- [x] Count the number of leaves in a tree.
- [x] Return the height of a tree.
- [x] Print In-order traversal of the tree.
- [x] Check if the tree is empty.
- [x] Print the tree showing its colors and structure. `(Using println!(“{:#?}”,tree);` is NOT sufficient)

**Note:** For both parts 1 and 2, you must use Rust smart pointers (preferably Rc and RefCell). Do not use raw pointers or unsafe code in any of your code.

To assist you with these parts, please ponder (and answer) the following questions as you go:
1. What does a red-black tree provide that cannot be accomplished with ordinary binary search trees?
2. Please add a command-line interface (function main) to your crate to allow users to test it.
3. Do you need to apply any kind of error handling in your system (e.g., panic macro, Option<T>, Result<T, E>, etc..)
4. What components do the Red-black tree and AVL tree have in common? Don’t Repeat Yourself! Never, ever repeat yourself – a fundamental idea in programming.
5. How do we construct our design to “allow it to be efficiently and effectively extended”?
For example. Could your code be reused to build a 2-3-4 tree or B tree?
